### ISSUE TITLE
Info about elixir drivers

### ISSUE THREAD

**Issue by tglman** [austinsmorris/orientex#1]
hi,

As far as i know there is already an elixir driver, here it is: https://github.com/MyMedsAndMe/marco_polo, do you have any reason for write another from scratch? i think the developers of marco_polo will welcome contributors.

In any case if you have to have fun to write a new one from scratch, enjoy it :D

Bye

**Comment by austinsmorris** [comment]
Hi @tglman,

Yes, I know about marco_polo.  I'm mostly just teaching myself elixir and orientdb, and learning a lot about both ecosystems in the process!

Cheers!

**Comment by austinsmorris** [comment]
@tglman, I see you are part of the orient organization.  Do you know anybody that could help with this?

http://stackoverflow.com/questions/38644653/systemd-stops-orientdb-immediately-after-it-starts-on-ubuntu-16-04

**Comment by tglman** [comment]
Hi @austinsmorris,

Like you saw on the other issue we are on it, i think your problem is just that you miss the user specified by systemd service on your system ;)
